[package]
name = "unterm-engine"
version = "0.1.0"
edition = "2018"
publish = false

[[bin]]
name = "unterm-next-core"
path = "src/bin/unterm-next-core.rs"

[dependencies]
anyhow.workspace = true
base64.workspace = true
parking_lot.workspace = true
portable-pty = { workspace = true, features = ["serde_support"] }
procinfo = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
freetype.workspace = true
harfbuzz.workspace = true
termwiz.workspace = true
unterm-protocol.workspace = true
unterm-images.workspace = true
